/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author megan
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        cuerpo = new javax.swing.JPanel();
        lateral = new javax.swing.JPanel();
        tabVenta = new javax.swing.JPanel();
        labelVenta = new javax.swing.JLabel();
        iconVenta = new javax.swing.JLabel();
        tabCatalogo = new javax.swing.JPanel();
        labelCatalogo = new javax.swing.JLabel();
        iconCatalogo = new javax.swing.JLabel();
        tabEcuaciones = new javax.swing.JPanel();
        labelEcuaciones = new javax.swing.JLabel();
        iconEcuaciones = new javax.swing.JLabel();
        tabProducto = new javax.swing.JPanel();
        labelProducto = new javax.swing.JLabel();
        iconProducto = new javax.swing.JLabel();
        tabRanking = new javax.swing.JPanel();
        labelRanking = new javax.swing.JLabel();
        iconRanking = new javax.swing.JLabel();
        tabBalance = new javax.swing.JPanel();
        labelBalance = new javax.swing.JLabel();
        iconBalance = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tabCompra = new javax.swing.JPanel();
        labelCompra = new javax.swing.JLabel();
        iconCompra = new javax.swing.JLabel();
        separadorLogo = new javax.swing.JSeparator();
        superior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        iconUsuario = new javax.swing.JLabel();
        iconNuevoUser = new javax.swing.JLabel();
        separadorUser = new javax.swing.JSeparator();
        iconListadoUser = new javax.swing.JLabel();
        iconAlerta = new javax.swing.JLabel();
        separadorUser2 = new javax.swing.JSeparator();
        separadorUser3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuerpo.setBackground(new java.awt.Color(32, 40, 51));

        javax.swing.GroupLayout cuerpoLayout = new javax.swing.GroupLayout(cuerpo);
        cuerpo.setLayout(cuerpoLayout);
        cuerpoLayout.setHorizontalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        cuerpoLayout.setVerticalGroup(
            cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        base.add(cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 990, 660));

        lateral.setBackground(new java.awt.Color(17, 19, 26));
        lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabVenta.setBackground(new java.awt.Color(17, 19, 26));
        tabVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabVentaMouseExited(evt);
            }
        });

        labelVenta.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelVenta.setForeground(new java.awt.Color(197, 198, 199));
        labelVenta.setText("Venta");
        labelVenta.setPreferredSize(new java.awt.Dimension(41, 20));

        iconVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buying_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabVentaLayout = new javax.swing.GroupLayout(tabVenta);
        tabVenta.setLayout(tabVentaLayout);
        tabVentaLayout.setHorizontalGroup(
            tabVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconVenta)
                .addGap(20, 20, 20)
                .addComponent(labelVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        tabVentaLayout.setVerticalGroup(
            tabVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lateral.add(tabVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 50));

        tabCatalogo.setBackground(new java.awt.Color(17, 19, 26));
        tabCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabCatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabCatalogoMouseExited(evt);
            }
        });

        labelCatalogo.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelCatalogo.setForeground(new java.awt.Color(197, 198, 199));
        labelCatalogo.setText("Catálogo");
        labelCatalogo.setPreferredSize(new java.awt.Dimension(41, 20));

        iconCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Price_Tag_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabCatalogoLayout = new javax.swing.GroupLayout(tabCatalogo);
        tabCatalogo.setLayout(tabCatalogoLayout);
        tabCatalogoLayout.setHorizontalGroup(
            tabCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCatalogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconCatalogo)
                .addGap(20, 20, 20)
                .addComponent(labelCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        tabCatalogoLayout.setVerticalGroup(
            tabCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCatalogoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lateral.add(tabCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 50));

        tabEcuaciones.setBackground(new java.awt.Color(17, 19, 26));
        tabEcuaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabEcuacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabEcuacionesMouseExited(evt);
            }
        });

        labelEcuaciones.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelEcuaciones.setForeground(new java.awt.Color(197, 198, 199));
        labelEcuaciones.setText("Cálculo de ecuaciones");
        labelEcuaciones.setPreferredSize(new java.awt.Dimension(41, 20));

        iconEcuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Test_Tube_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabEcuacionesLayout = new javax.swing.GroupLayout(tabEcuaciones);
        tabEcuaciones.setLayout(tabEcuacionesLayout);
        tabEcuacionesLayout.setHorizontalGroup(
            tabEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEcuacionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconEcuaciones)
                .addGap(18, 18, 18)
                .addComponent(labelEcuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        tabEcuacionesLayout.setVerticalGroup(
            tabEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEcuacionesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tabEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconEcuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEcuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lateral.add(tabEcuaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 50));

        tabProducto.setBackground(new java.awt.Color(17, 19, 26));
        tabProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabProductoMouseExited(evt);
            }
        });

        labelProducto.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelProducto.setForeground(new java.awt.Color(197, 198, 199));
        labelProducto.setText("Nuevo producto");
        labelProducto.setPreferredSize(new java.awt.Dimension(41, 20));

        iconProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_Tag_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabProductoLayout = new javax.swing.GroupLayout(tabProducto);
        tabProducto.setLayout(tabProductoLayout);
        tabProductoLayout.setHorizontalGroup(
            tabProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconProducto)
                .addGap(20, 20, 20)
                .addComponent(labelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        tabProductoLayout.setVerticalGroup(
            tabProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lateral.add(tabProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 50));

        tabRanking.setBackground(new java.awt.Color(17, 19, 26));
        tabRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabRankingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabRankingMouseExited(evt);
            }
        });

        labelRanking.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelRanking.setForeground(new java.awt.Color(197, 198, 199));
        labelRanking.setText("Productos más vendidos");
        labelRanking.setPreferredSize(new java.awt.Dimension(41, 20));

        iconRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Best_Seller_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabRankingLayout = new javax.swing.GroupLayout(tabRanking);
        tabRanking.setLayout(tabRankingLayout);
        tabRankingLayout.setHorizontalGroup(
            tabRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRankingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconRanking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(labelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        tabRankingLayout.setVerticalGroup(
            tabRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRankingLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lateral.add(tabRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 50));

        tabBalance.setBackground(new java.awt.Color(17, 19, 26));
        tabBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabBalanceMouseExited(evt);
            }
        });

        labelBalance.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelBalance.setForeground(new java.awt.Color(197, 198, 199));
        labelBalance.setText("Balance de ventas");
        labelBalance.setPreferredSize(new java.awt.Dimension(41, 20));

        iconBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Stocks_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabBalanceLayout = new javax.swing.GroupLayout(tabBalance);
        tabBalance.setLayout(tabBalanceLayout);
        tabBalanceLayout.setHorizontalGroup(
            tabBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBalanceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        tabBalanceLayout.setVerticalGroup(
            tabBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBalanceLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconBalance))
                .addContainerGap())
        );

        lateral.add(tabBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 50));

        jLabel19.setFont(new java.awt.Font("Fira Sans Book", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Logo");
        lateral.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 230));

        tabCompra.setBackground(new java.awt.Color(17, 19, 26));
        tabCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabCompraMouseExited(evt);
            }
        });

        labelCompra.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        labelCompra.setForeground(new java.awt.Color(197, 198, 199));
        labelCompra.setText("Compra");
        labelCompra.setPreferredSize(new java.awt.Dimension(41, 20));

        iconCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buy_32px.png"))); // NOI18N

        javax.swing.GroupLayout tabCompraLayout = new javax.swing.GroupLayout(tabCompra);
        tabCompra.setLayout(tabCompraLayout);
        tabCompraLayout.setHorizontalGroup(
            tabCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCompraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        tabCompraLayout.setVerticalGroup(
            tabCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCompraLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lateral.add(tabCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 290, 50));

        separadorLogo.setForeground(new java.awt.Color(32, 40, 51));
        lateral.add(separadorLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 270, 10));

        base.add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 720));

        superior.setBackground(new java.awt.Color(24, 30, 38));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Fira Sans Book", 0, 21)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(197, 198, 199));
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUsuario.setText("Usuario12345678");

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_32px.png"))); // NOI18N
        iconUsuario.setToolTipText("Usuario");
        iconUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconUsuarioMouseExited(evt);
            }
        });

        iconNuevoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_User_Male_32px.png"))); // NOI18N
        iconNuevoUser.setToolTipText("Nuevo usuario");
        iconNuevoUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconNuevoUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconNuevoUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconNuevoUserMouseExited(evt);
            }
        });

        separadorUser.setOrientation(javax.swing.SwingConstants.VERTICAL);

        iconListadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_Account_32px.png"))); // NOI18N
        iconListadoUser.setToolTipText("Lista de usuarios");
        iconListadoUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconListadoUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconListadoUserMouseExited(evt);
            }
        });

        iconAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Box_Important_32px.png"))); // NOI18N
        iconAlerta.setToolTipText("Alerta");
        iconAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconAlertaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconAlertaMouseExited(evt);
            }
        });

        separadorUser2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        separadorUser3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                .addContainerGap(813, Short.MAX_VALUE)
                .addComponent(iconAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(iconListadoUser)
                .addGap(12, 12, 12)
                .addComponent(separadorUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconNuevoUser)
                .addGap(11, 11, 11)
                .addComponent(separadorUser, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cerrar)
                .addContainerGap())
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorLayout.createSequentialGroup()
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(superiorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(iconUsuario)
                            .addComponent(labelUsuario)
                            .addComponent(iconListadoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconNuevoUser)
                            .addComponent(iconAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separadorUser3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separadorUser)
                            .addComponent(cerrar)))
                    .addGroup(superiorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(separadorUser2)))
                .addGap(12, 12, 12))
        );

        base.add(superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVentaMouseEntered
        this.labelVenta.setForeground(new Color(102,252,241));
        this.iconVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buying_32px_1.png")));
    }//GEN-LAST:event_tabVentaMouseEntered

    private void tabVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVentaMouseExited
        this.labelVenta.setForeground(new Color(197,198,199));
        this.iconVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buying_32px.png")));
    }//GEN-LAST:event_tabVentaMouseExited

    private void tabCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCatalogoMouseEntered
        this.labelCatalogo.setForeground(new Color(102,252,241));
        this.iconCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Price_Tag_32px_1.png")));
    }//GEN-LAST:event_tabCatalogoMouseEntered

    private void tabCatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCatalogoMouseExited
        this.labelCatalogo.setForeground(new Color(197,198,199));
        this.iconCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Price_Tag_32px.png")));
    }//GEN-LAST:event_tabCatalogoMouseExited

    private void tabProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductoMouseEntered
        this.labelProducto.setForeground(new Color(102,252,241));
        this.iconProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_Tag_32px_1.png")));
    }//GEN-LAST:event_tabProductoMouseEntered

    private void tabProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductoMouseExited
        this.labelProducto.setForeground(new Color(197,198,199));
        this.iconProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_Tag_32px.png")));
    }//GEN-LAST:event_tabProductoMouseExited

    private void tabRankingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRankingMouseEntered
        this.labelRanking.setForeground(new Color(102,252,241));
        this.iconRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Best_Seller_32px_1.png")));
    }//GEN-LAST:event_tabRankingMouseEntered

    private void tabRankingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRankingMouseExited
         this.labelRanking.setForeground(new Color(197,198,199));
         this.iconRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Best_Seller_32px.png")));
    }//GEN-LAST:event_tabRankingMouseExited

    private void tabBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBalanceMouseEntered
        this.labelBalance.setForeground(new Color(102,252,241));
        this.iconBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Stocks_32px_1.png")));
    }//GEN-LAST:event_tabBalanceMouseEntered

    private void tabBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBalanceMouseExited
        this.labelBalance.setForeground(new Color(197,198,199));
        this.iconBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Stocks_32px.png")));
    }//GEN-LAST:event_tabBalanceMouseExited

    private void tabCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCompraMouseEntered
        this.labelCompra.setForeground(new Color(102,252,241));
        this.iconCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buy_32px_1.png")));
    }//GEN-LAST:event_tabCompraMouseEntered

    private void tabCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCompraMouseExited
        this.labelCompra.setForeground(new Color(197,198,199));
        this.iconCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Buy_32px.png")));
    }//GEN-LAST:event_tabCompraMouseExited

    private void tabEcuacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEcuacionesMouseEntered
        this.labelEcuaciones.setForeground(new Color(102,252,241));
        this.iconEcuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Test_Tube_32px_1.png")));
    }//GEN-LAST:event_tabEcuacionesMouseEntered

    private void tabEcuacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEcuacionesMouseExited
        this.labelEcuaciones.setForeground(new Color(197,198,199));
        this.iconEcuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Test_Tube_32px.png")));
    }//GEN-LAST:event_tabEcuacionesMouseExited

    private void iconAlertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAlertaMouseEntered
        this.iconAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Box_Important_32px_1.png")));
    }//GEN-LAST:event_iconAlertaMouseEntered

    private void iconAlertaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAlertaMouseExited
        this.iconAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Box_Important_32px.png")));
    }//GEN-LAST:event_iconAlertaMouseExited

    private void iconListadoUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconListadoUserMouseEntered
        this.iconListadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_Account_32px_1.png")));
    }//GEN-LAST:event_iconListadoUserMouseEntered

    private void iconListadoUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconListadoUserMouseExited
        this.iconListadoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_Account_32px.png")));
    }//GEN-LAST:event_iconListadoUserMouseExited

    private void iconNuevoUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconNuevoUserMouseEntered
        this.iconNuevoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_User_Male_32px_1.png")));
    }//GEN-LAST:event_iconNuevoUserMouseEntered

    private void iconNuevoUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconNuevoUserMouseExited
        this.iconNuevoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Add_User_Male_32px.png")));
    }//GEN-LAST:event_iconNuevoUserMouseExited

    private void iconUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUsuarioMouseEntered
        this.iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_32px_1.png")));
    }//GEN-LAST:event_iconUsuarioMouseEntered

    private void iconUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUsuarioMouseExited
        this.iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_User_32px.png")));
    }//GEN-LAST:event_iconUsuarioMouseExited

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        this.cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Multiply_32px_1.png")));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        this.cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icons/icons8_Multiply_32px.png")));
    }//GEN-LAST:event_cerrarMouseExited

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel iconAlerta;
    private javax.swing.JLabel iconBalance;
    private javax.swing.JLabel iconCatalogo;
    private javax.swing.JLabel iconCompra;
    private javax.swing.JLabel iconEcuaciones;
    private javax.swing.JLabel iconListadoUser;
    private javax.swing.JLabel iconNuevoUser;
    private javax.swing.JLabel iconProducto;
    private javax.swing.JLabel iconRanking;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JLabel iconVenta;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelCatalogo;
    private javax.swing.JLabel labelCompra;
    private javax.swing.JLabel labelEcuaciones;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelRanking;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelVenta;
    private javax.swing.JPanel lateral;
    private javax.swing.JSeparator separadorLogo;
    private javax.swing.JSeparator separadorUser;
    private javax.swing.JSeparator separadorUser2;
    private javax.swing.JSeparator separadorUser3;
    private javax.swing.JPanel superior;
    private javax.swing.JPanel tabBalance;
    private javax.swing.JPanel tabCatalogo;
    private javax.swing.JPanel tabCompra;
    private javax.swing.JPanel tabEcuaciones;
    private javax.swing.JPanel tabProducto;
    private javax.swing.JPanel tabRanking;
    private javax.swing.JPanel tabVenta;
    // End of variables declaration//GEN-END:variables
}
